### ISSUE TITLE
ch02: Ingress pods stay unschedulable

### ISSUE THREAD

**Issue by m-czernek** [PacktPublishing/Kubernetes---An-Enterprise-Guide-2E#11]
When executing the section `Installing an Ingress Controller`, readers are pointed to the following command:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
```

However, the deployment contains the following node selector:

```
$ kubectl get deployments.apps -o yaml -n ingress-nginx | grep nodeSelector -A2
        nodeSelector:
          ingress-ready: "true"
          kubernetes.io/os: linux
```

The [clister01-kind.yaml](https://github.com/PacktPublishing/Kubernetes---An-Enterprise-Guide-2E/tree/main/chapter2/cluster01-kind.yaml) file does not add the required label to any node.

As per the [create cluster](https://kind.sigs.k8s.io/docs/user/ingress/#create-cluster) docs, you should add the node selector to the config file.

A workaround is to apply the label manually, e.g.:

```
kubectl label nodes cluster01-control-plane ingress-ready=true
```

**Comment by ssurovich** [comment]
Yeah, the scripted installation adds that label, you can do it manually as you found out as well.
