### ISSUE TITLE
openunison image not available

### ISSUE THREAD

**Issue by tsigian** [PacktPublishing/Kubernetes---An-Enterprise-Guide-2E#2]
Chapter 8 in openunison-values.yaml, the image _docker.lab.tremolo.dev/lab/ou-k8s_ seems to not be reachable. 

Tried also with the _docker.io/tremolosecurity/openunison-k8s-login-activedirectory:latest_ image which was available, but the  'openunison-orchestra' pod was failing on the readiness probes.

**Comment by mlbiam** [comment]
sorry about that @tsigian, the right image is `docker.io/tremolosecurity/openunison-k8s:latest`.  I updated the values.yaml

**Comment by tsigian** [comment]
Thank you.

Now it fails to pull another image :

`$ helm install orchestra-login-portal tremolo/orchestra-login-portal --namespace openunison -f openunison-values.yaml

.....
Failed to pull image "docker.lab.tremolo.dev/nginx": rpc error: code = Unknown desc = failed to pull and unpack image "docker.lab.tremolo.dev/nginx:latest": failed to resolve reference "docker.lab.tremolo.dev/nginx:latest":`

**Comment by mlbiam** [comment]
Should be good now.  don't see any more references to my lab network in any of the samples

**Comment by tsigian** [comment]
It works now thank you
