### ISSUE TITLE
falco-functions pod fails

### ISSUE THREAD

**Issue by tsigian** [PacktPublishing/Kubernetes---An-Enterprise-Guide-2E#4]
Chapter 10

fulco-functions pod readiness probe fails, looks like the HTTP server is unreachable:

> $ k describe pod falco-functions-7c647fbb8f-xlf2c
> 
> Warning  Unhealthy  21s (x9 over 5m21s)    kubelet            Liveness probe failed: Get "http://10.240.189.142:8080/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> 

Tried from inside the container also:

> $ k exec -it falco-functions-7c647fbb8f-xlf2c -- bash
>
> Defaulted container "falco-functions" out of: falco-functions, prepare (init), install (init)
> I have no name!@falco-functions-7c647fbb8f-xlf2c:/$ curl -v localhost:8080
> * Rebuilt URL to: localhost:8080/
> *   Trying ::1...
> * TCP_NODELAY set
> * connect to ::1 port 8080 failed: Connection refused
> *   Trying 127.0.0.1...
> * TCP_NODELAY set
> * Connected to localhost (127.0.0.1) port 8080 (#0)
>  GET / HTTP/1.1
>  Host: localhost:8080
>  User-Agent: curl/7.52.1
>  Accept: */*
> 
> I have no name!@falco-functions-7c647fbb8f-xlf2c:/$ curl -v localhost:8080/healthz
> *   Trying ::1...
> * TCP_NODELAY set
> * connect to ::1 port 8080 failed: Connection refused
> *   Trying 127.0.0.1...
> * TCP_NODELAY set
> * Connected to localhost (127.0.0.1) port 8080 (#0)
>  GET /healthz HTTP/1.1
>  Host: localhost:8080
>  User-Agent: curl/7.52.1
>  Accept: */*

**Comment by ssurovich** [comment]
Hi @tsigian - Apologies, I didnt see this issue sooner, is this still an issue for you?   I can look into it ASAP, just want to confirm you are still having the issue.

**Comment by tsigian** [comment]
I will try it again this week and let you know @ssurovich

**Comment by ssurovich** [comment]
Hi @tsigian  -  Just checking to see if you had a chance to test again?   No rush, but just curious.

**Comment by tsigian** [comment]
Sorry I haven't. I'll close the issue for now.

**Comment by ssurovich** [comment]
No worries at all, Im sure you are busy, like most IT people :)   Im going to spin up a new VM and verify it from my side today as well - I'll reply with my findings, and if required, any changes I needed to make.

**Comment by ssurovich** [comment]
Hi @tsigian - I just tested the script and exercises for Chapter 10 and  the functions pod deployed for me without CrashLooping - a curl on the healthz endpoint also succeeded for me:

$ curl 127.0.0.1:8080/healthz
OK$

If you do happen to have the issue when you test it again, please let me now - I would like to make sure you can successfully test the kubeless fuctions exercise (It's one of my favorite demos to show people)
