### ISSUE TITLE
"ou-tls-certificate" not found

### ISSUE THREAD

**Issue by tsigian** [PacktPublishing/Kubernetes---An-Enterprise-Guide-2E#5]
**CHAPTER 14**

After run the './deploy_openunison_imp.sh' script, the 'kube-oidc-proxy-orchestra' pod fails.

The problem seems to be with a secret that has the wrong name. It has extra characters, eg 'ou-tls-certificate-8b9md' instead of 'ou-tls-certificate'.

I changed it's name to 'ou-tls-certificate' and it partially worked. The next error is that the secret holds only the private key and not the private key and the certificate.

### first error
  **Warning  FailedMount  16s (x12 over 10m)     kubelet            MountVolume.SetUp failed for volume "kube-oidc-proxy-config" : secret "ou-tls-certificate" not found**

### second error after the secret rename
  **Warning  FailedMount  12s (x6 over 28s)  kubelet            MountVolume.SetUp failed for volume "kube-oidc-proxy-config" : references non-existent secret key: tls.crt**

**Comment by mlbiam** [comment]
> 'ou-tls-certificate-8b9md' instead of 'ou-tls-certificate'.

This means that cert manager didn't issue the certificate. That's why there's only a `tls.key` in the `Secret`. 

There should be a `ou-tls-certificate` `Certificate` object in the `openunison` namespace. The status section should have an error saying why the cert wasn't issued.

**Comment by tsigian** [comment]
Thank you it's fixed now. It was an issue with the openssl v3 extensions.
