### ISSUE TITLE
Gitlab username

### ISSUE THREAD

**Issue by tsigian** [PacktPublishing/Kubernetes---An-Enterprise-Guide-2E#6]
CHAPTER 14

Able to get the Gitlab password with: 
`kubectl get secret gitlab-gitlab-initial-root-password -o json -n gitlab | jq -r '.data.password' | base64 -d`

..but can't find the username to login, tried 'git', 'gitlab', 'Git', 'Gitlab' but none of them worked.

**Comment by mlbiam** [comment]
Default initial user is `root`

**Comment by tsigian** [comment]
worked thank you.
