### ISSUE TITLE
Gatekeeper API versions issue

### ISSUE THREAD

**Issue by tsigian** [PacktPublishing/Kubernetes---An-Enterprise-Guide-2E#7]
CHAPTER 14

Deploying gatekeeper has issues with gatekeeper API versions:

> $ ./deploy_gatekeeper.sh
namespace/gatekeeper-system created
customresourcedefinition.apiextensions.k8s.io/assign.mutations.gatekeeper.sh created
customresourcedefinition.apiextensions.k8s.io/assignmetadata.mutations.gatekeeper.sh created
resourcequota/gatekeeper-critical-pods created
customresourcedefinition.apiextensions.k8s.io/configs.config.gatekeeper.sh created
customresourcedefinition.apiextensions.k8s.io/constraintpodstatuses.status.gatekeeper.sh created
customresourcedefinition.apiextensions.k8s.io/constrainttemplatepodstatuses.status.gatekeeper.sh created
customresourcedefinition.apiextensions.k8s.io/constrainttemplates.templates.gatekeeper.sh created
mutatingwebhookconfiguration.admissionregistration.k8s.io/gatekeeper-mutating-webhook-configuration created
customresourcedefinition.apiextensions.k8s.io/mutatorpodstatuses.status.gatekeeper.sh created
serviceaccount/gatekeeper-admin created
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
podsecuritypolicy.policy/gatekeeper-admin created
role.rbac.authorization.k8s.io/gatekeeper-manager-role created
clusterrole.rbac.authorization.k8s.io/gatekeeper-manager-role created
rolebinding.rbac.authorization.k8s.io/gatekeeper-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/gatekeeper-manager-rolebinding created
secret/gatekeeper-webhook-server-cert created
service/gatekeeper-webhook-service created
deployment.apps/gatekeeper-audit created
deployment.apps/gatekeeper-controller-manager created
Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
poddisruptionbudget.policy/gatekeeper-controller-manager created
validatingwebhookconfiguration.admissionregistration.k8s.io/gatekeeper-validating-webhook-configuration created
sleeping 10 seconds
usage: sleep seconds
error: unable to recognize "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/pod-security-policy/allow-privilege-escalation/template.yaml": no matches for kind "ConstraintTemplate" in version "templates.gatekeeper.sh/v1"
error: unable to recognize "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/pod-security-policy/capabilities/template.yaml": no matches for kind "ConstraintTemplate" in version "templates.gatekeeper.sh/v1"
error: unable to recognize "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/pod-security-policy/forbidden-sysctls/template.yaml": no matches for kind "ConstraintTemplate" in version "templates.gatekeeper.sh/v1"
error: unable to recognize "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/pod-security-policy/host-filesystem/template.yaml": no matches for kind "ConstraintTemplate" in version "templates.gatekeeper.sh/v1"
error: unable to recognize "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/pod-security-policy/host-namespaces/template.yaml": no matches for kind "ConstraintTemplate" in version "templates.gatekeeper.sh/v1"
error: unable to recognize "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/pod-security-policy/host-network-ports/template.yaml": no matches for kind "ConstraintTemplate" in version "templates.gatekeeper.sh/v1"
error: unable to recognize "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/pod-security-policy/privileged-containers/template.yaml": no matches for kind "ConstraintTemplate" in version "templates.gatekeeper.sh/v1"
error: unable to recognize "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/pod-security-policy/proc-mount/template.yaml": no matches for kind "ConstraintTemplate" in version "templates.gatekeeper.sh/v1"
error: unable to recognize "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/pod-security-policy/read-only-root-filesystem/template.yaml": no matches for kind "ConstraintTemplate" in version "templates.gatekeeper.sh/v1"
error: unable to recognize "https://raw.githubusercontent.com/open-policy-agent/gatekeeper-library/master/library/pod-security-policy/users/template.yaml": no matches for kind "ConstraintTemplate" in version "templates.gatekeeper.sh/v1"
sleeping 10 seconds
usage: sleep seconds
assign.mutations.gatekeeper.sh/k8spspdefaultallowprivilegeescalation created
assign.mutations.gatekeeper.sh/k8spspdefaultallowprivilegeescalationinit created
assign.mutations.gatekeeper.sh/k8spspfsgroup created

**Comment by ssurovich** [comment]
@mlbiam - Another one if you get a chance.

@tsigian - What is your host OS for the exercises?

**Comment by tsigian** [comment]
@ssurovich Ubuntu 20.4 (Virtualbox), and also my Macbook with Docker desktop. I use both of them for the exercises.

**Comment by mlbiam** [comment]
@tsigian i'm sorry.  i took WAY too long to get to this but you're right and it's fixed.  i had to pin the specific commits.
